# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "cachescrubber"

  # Maven: only patch updates to release/1.0.x
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/1.0.x"
    reviewers:
      - "cachescrubber"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
    groups:
      maven-patch:
        update-types:
          - "patch"

  # Maven: minor + patch updates to master
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "cachescrubber"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      maven-patch:
        update-types:
          - "patch"
