# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "cachescrubber"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    reviewers:
      - "cachescrubber"
    groups:
      maven-patch:
        applies-to: version-updates
        update-types: [ "patch" ]
        target-branch: release/1.0.x
        reviewers:
          - "cachescrubber"
      maven-minor-patch:
        applies-to: version-updates
        update-types: [ "minor", "patch" ]
        target-branch: master
        reviewers:
          - "cachescrubber"
